12/28 19:56:44 INFO |       pts:0062| 0
12/28 19:56:44 INFO |       pts:0063| now start first expect.........
12/28 19:56:44 INFO |       pts:0081| now start run test..............
12/28 20:15:45 ERROR|      test:0414| Exception escaping from test:
Traceback (most recent call last):
  File "/root/autotest/client/shared/test.py", line 411, in _exec
    _call_test_function(self.execute, *p_args, **p_dargs)
  File "/root/autotest/client/shared/test.py", line 830, in _call_test_function
    raise error.UnhandledTestFail(e)
UnhandledTestFail: Unhandled TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7ff3b051a9d0>
command: /bin/phoronix-test-suite
args: ['/bin/phoronix-test-suite', 'run', 'compiler']
searcher: None
buffer (last 100 chars): ' n\r\n    Would you like to upload the results to OpenBenchmarking.org (Y/n): '
before (last 100 chars): ' n\r\n    Would you like to upload the results to OpenBenchmarking.org (Y/n): '
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 3131
child_fd: 21
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: <open file '/home/Linux-version-test-result/PTS_compiler/results/default/pts.compiler/results/raw_output_compiler', mode 'w' at 0x7ff3b0523390>
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
Traceback (most recent call last):
  File "/root/autotest/client/shared/test.py", line 823, in _call_test_function
    return func(*args, **dargs)
  File "/root/autotest/client/shared/test.py", line 291, in execute
    postprocess_profiled_run, args, dargs)
  File "/root/autotest/client/shared/test.py", line 212, in _call_run_once
    self.run_once(*args, **dargs)
  File "/root/autotest/client/tests/pts/pts.py", line 93, in run_once
    runpts.expect(pexpect.EOF)
  File "/usr/lib/python2.7/site-packages/pexpect/spawnbase.py", line 315, in expect
    timeout, searchwindowsize, async)
  File "/usr/lib/python2.7/site-packages/pexpect/spawnbase.py", line 339, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/lib/python2.7/site-packages/pexpect/expect.py", line 104, in expect_loop
    return self.timeout(e)
  File "/usr/lib/python2.7/site-packages/pexpect/expect.py", line 68, in timeout
    raise TIMEOUT(msg)
TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7ff3b051a9d0>
command: /bin/phoronix-test-suite
args: ['/bin/phoronix-test-suite', 'run', 'compiler']
searcher: None
buffer (last 100 chars): ' n\r\n    Would you like to upload the results to OpenBenchmarking.org (Y/n): '
before (last 100 chars): ' n\r\n    Would you like to upload the results to OpenBenchmarking.org (Y/n): '
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 3131
child_fd: 21
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: <open file '/home/Linux-version-test-result/PTS_compiler/results/default/pts.compiler/results/raw_output_compiler', mode 'w' at 0x7ff3b0523390>
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1

